# ============================================================
#  watchdog_daemon.py — Ledger Nexus IPFS Watchdog
#
#  Pipeline:
#    1. Analyse tx → build JSON report → AES-256-GCM encrypt
#    2. Save to disk
#    3. Pin to Pinata IPFS (real) or return mock CID (demo)
#    4. Optionally fetch & decrypt a stored report
# ============================================================

import json
import os
import uuid
import base64
import requests
from datetime import datetime, timezone
from pathlib import Path

# ── AES import: try pycryptodome (preferred), then pycryptodomex ─
try:
    from Cryptodome.Cipher import AES
except ImportError:
    from Crypto.Cipher import AES

from config import (
    PINATA_JWT,
    PINATA_UPLOAD_URL,
    PINATA_GATEWAY,
    AMOUNT_FLAG_THRESHOLD,
    UNVERIFIED_CONTRACTORS,
    REPORT_OUTPUT_DIR,
    WATCHDOG_VERSION,
)


# ────────────────────────────────────────────────────────────
#  AES-256-GCM ENCRYPTION
# ────────────────────────────────────────────────────────────

def encrypt_report(report_json_str: str, hex_key: str) -> str:
    """Encrypt a JSON string with AES-256-GCM using the NFC-derived key."""
    if not hex_key:
        return report_json_str
    key_bytes = bytes.fromhex(hex_key.replace("0x", ""))
    cipher = AES.new(key_bytes, AES.MODE_GCM)
    ciphertext, tag = cipher.encrypt_and_digest(report_json_str.encode("utf-8"))
    payload = cipher.nonce + tag + ciphertext
    return base64.b64encode(payload).decode("utf-8")


def decrypt_report(encrypted_b64: str, hex_key: str) -> str:
    """Decrypt an AES-256-GCM payload produced by encrypt_report."""
    if not hex_key:
        raise ValueError("NFC hardware key required for decryption.")
    key_bytes = bytes.fromhex(hex_key.replace("0x", ""))
    payload   = base64.b64decode(encrypted_b64)
    nonce, tag, ciphertext = payload[:16], payload[16:32], payload[32:]
    cipher = AES.new(key_bytes, AES.MODE_GCM, nonce=nonce)
    return cipher.decrypt_and_verify(ciphertext, tag).decode("utf-8")


# ────────────────────────────────────────────────────────────
#  SUSPICIOUS TX ANALYSIS
# ────────────────────────────────────────────────────────────

def _build_flags(tx: dict) -> list:
    flags = []
    if tx.get("amount_eth", 0) > AMOUNT_FLAG_THRESHOLD:
        flags.append("AMOUNT_EXCEEDS_THRESHOLD")
    if tx.get("to") in UNVERIFIED_CONTRACTORS:
        flags.append("UNVERIFIED_CONTRACTOR")
    if tx.get("rapid_succession", False):
        flags.append("RAPID_SUCCESSION_TX")
    if tx.get("no_purpose_string", False):
        flags.append("MISSING_PURPOSE_FIELD")
    return flags or ["GENERIC_ANOMALY"]


def generate_suspicious_report(tx: dict = None) -> dict:
    """
    Build a detailed audit report dict for a suspicious transaction.
    If tx is None, a realistic mock transaction is generated for demo runs.
    """
    if tx is None:
        tx = {
            "hash":             "0xc0ffee1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
            "from":             "0xAdminWallet000000000000000000000000000001",
            "to":               "0xDEADBEEF00000000000000000000000000000001",
            "amount_eth":       450_000.00,
            "block":            19_203_455,
            "rapid_succession": True,
            "no_purpose_string": True,
        }

    flags    = _build_flags(tx)
    tx["flags"] = flags  # Inject flags so AI can read them
    
    # ── AI Ensemble Evaluation ──
    try:
        from ai_watchdog import evaluate_transaction
        ai_insights = evaluate_transaction(tx)
    except Exception as e:
        ai_insights = {
            "is_anomaly": False, 
            "knn_distance": 0, 
            "confidence_score": 0, 
            "semantic_analysis": f"AI Engine Offline: {e}"
        }

    # If AI flags it as an anomaly, escalate severity
    severity = "CRITICAL" if (len(flags) >= 3 or ai_insights.get("is_anomaly")) else ("HIGH" if len(flags) >= 2 else "MEDIUM")

    return {
        "report_id":        str(uuid.uuid4()),
        "generated_at":     datetime.now(timezone.utc).isoformat(),
        "watchdog_version": WATCHDOG_VERSION,
        "transaction": {
            "hash":       tx.get("hash",       "N/A"),
            "from":       tx.get("from",       "N/A"),
            "to":         tx.get("to",         "N/A"),
            "amount_eth": tx.get("amount_eth",  0.0),
            "block":      tx.get("block",       0),
        },
        "flags":           flags,
        "flag_count":      len(flags),
        "severity":        severity,
        "action_required": severity in ("CRITICAL", "HIGH"),
        "ai_insights":     ai_insights,
        "notes": (
            "Auto-generated by Ledger Nexus AI Watchdog. "
            "This report has been pinned to IPFS for tamper-proof archival."
        ),
    }


# ────────────────────────────────────────────────────────────
#  PERSIST & UPLOAD
# ────────────────────────────────────────────────────────────

def save_report_to_file(report: dict, aes_key: str = None) -> Path:
    """Serialise the report dict to a JSON file, optionally AES-encrypted."""
    out_dir = Path(REPORT_OUTPUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"audit_{report['report_id'][:8]}_{ts}.json"
    filepath = out_dir / filename

    if aes_key:
        print("[WATCHDOG] 🔒 Encrypting audit payload with NFC hardware key…")
        encrypted = encrypt_report(json.dumps(report), aes_key)
        out_data  = {"encrypted_payload": encrypted, "locked": True}
    else:
        out_data = report

    filepath.write_text(json.dumps(out_data, indent=2), encoding="utf-8")
    print(f"[WATCHDOG] Report saved → {filepath}")
    return filepath


def upload_to_pinata(filepath: Path) -> str:
    """Upload a JSON report to IPFS via Pinata. Returns CID or mock CID."""
    if PINATA_JWT == "YOUR_PINATA_JWT_HERE":
        mock_cid = "QmMock" + uuid.uuid4().hex[:40]
        print(f"[WATCHDOG] ⚡ Demo mode — mock CID: {mock_cid}")
        return mock_cid

    headers = {"Authorization": f"Bearer {PINATA_JWT}"}
    try:
        with open(filepath, "rb") as f:
            response = requests.post(
                PINATA_UPLOAD_URL,
                headers=headers,
                files={"file": (filepath.name, f, "application/json")},
                data={
                    "pinataMetadata": json.dumps({"name": filepath.name}),
                    "pinataOptions":  json.dumps({"cidVersion": 1}),
                },
                timeout=30,
            )
        if response.status_code == 200:
            cid = response.json()["IpfsHash"]
            print(f"[WATCHDOG] ✅ IPFS CID: {cid}")
            return cid
        print(f"[WATCHDOG] ❌ Pinata error {response.status_code}: {response.text}")
    except Exception as exc:
        print(f"[WATCHDOG] ❌ Upload error: {exc}")
    return None


# ────────────────────────────────────────────────────────────
#  FETCH & DECRYPT FROM IPFS / DISK
# ────────────────────────────────────────────────────────────

def fetch_ipfs_report(cid: str, aes_key: str = None) -> dict:
    """
    Fetch an audit report by CID.
    Tries the Pinata gateway first (when JWT is set), then falls back
    to the local reports directory.
    """
    # Try Pinata gateway if JWT is configured
    if PINATA_JWT != "YOUR_PINATA_JWT_HERE":
        try:
            url = f"{PINATA_GATEWAY}{cid}"
            resp = requests.get(url, timeout=10)
            if resp.status_code == 200:
                data = resp.json()
                return _decrypt_if_needed(data, aes_key)
        except Exception as exc:
            print(f"[WATCHDOG] IPFS gateway fetch failed: {exc}")

    # Fall back to local disk
    out_dir = Path(REPORT_OUTPUT_DIR)
    for candidate in sorted(out_dir.glob("*.json"), reverse=True):
        try:
            data = json.loads(candidate.read_text(encoding="utf-8"))
            return _decrypt_if_needed(data, aes_key)
        except Exception:
            continue

    return {"error": f"Report CID '{cid}' not found locally or on IPFS."}


def _decrypt_if_needed(data: dict, aes_key: str) -> dict:
    if data.get("locked"):
        if not aes_key:
            return {"error": "HARDWARE KEY REQUIRED — Tap Auditor NFC tag to decrypt."}
        decrypted = decrypt_report(data["encrypted_payload"], aes_key)
        return json.loads(decrypted)
    return data


# ────────────────────────────────────────────────────────────
#  ON-CHAIN VERIFICATION STUB (teammate fills in)
# ────────────────────────────────────────────────────────────

def verify_on_chain(tx_hash: str) -> bool:
    """
    Verify a transaction hash exists on the deployed contract.
    Imports CONTRACT_INSTANCE from ui_dashboard at runtime to avoid circular deps.
    """
    try:
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent / "ui"))
        import ui_dashboard as dash
        if dash.CONTRACT_INSTANCE and dash.W3_INSTANCE:
            # Check the receipt exists on-chain
            receipt = dash.W3_INSTANCE.eth.get_transaction_receipt(tx_hash)
            return receipt is not None and receipt.status == 1
    except Exception as exc:
        print(f"[WATCHDOG] verify_on_chain: {exc}")
    return False


# ────────────────────────────────────────────────────────────
#  FULL PIPELINE
# ────────────────────────────────────────────────────────────

def run_watchdog(tx: dict = None, aes_key: str = None) -> dict:
    """Full watchdog pipeline: analyse → save → upload → return result dict."""
    print("[WATCHDOG] 🚨 Suspicious transaction detected — running pipeline…")

    report   = generate_suspicious_report(tx)
    print(f"[WATCHDOG] Severity: {report['severity']} | Flags: {report['flags']}")

    filepath = save_report_to_file(report, aes_key=aes_key)
    cid      = upload_to_pinata(filepath)

    result = {
        "report":      report,
        "filepath":    str(filepath),
        "cid":         cid,
        "gateway_url": f"{PINATA_GATEWAY}{cid}" if cid else None,
    }
    print("[WATCHDOG] Pipeline complete.")
    return result


# ────────────────────────────────────────────────────────────
#  CLI entry-point
# ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    result = run_watchdog()
    print("\n── Result ──────────────────────────────────────────────")
    print(json.dumps(result["report"], indent=2))
    if result["cid"]:
        print(f"\n🔗 IPFS CID : {result['cid']}")
        print(f"🌐 Gateway  : {result['gateway_url']}")
